DROP TABLE FISH;
CREATE TABLE FISH(
   FISH_ID INT, --IDENTITY(1,1)
   Regions   VARCHAR (200) NOT NULL DEFAULT 'Lake',
   FishType    VARCHAR (30)	NOT NULL DEFAULT 'Fish',
   FishName    VARCHAR (50)		NOT NULL,
   Rarity VARCHAR (20)		NOT NULL,
   SetName VARCHAR (500) NULL,
   MIN_WEIGHT FLOAT NOT NULL,
   MAX_WEIGHT FLOAT NOT NULL,
   MIN_LENGTH FLOAT NOT NULL,
   MAX_LENGTH FLOAT NOT NULL,
   MIN_WIDTH FLOAT NOT NULL,
   MAX_WIDTH FLOAT NOT NULL,
   AVG_DEPTH FLOAT NULL,
   Preferred_Bait VARCHAR (50) DEFAULT 'Normal',
   Nocturnal INT DEFAULT 0,
   Seasonal VARCHAR(15) NULL,
   PRIMARY KEY (FISH_ID)

   --TW_Bronze FLOAT NOT NULL DEFAULT 60,
   --TW_Silver FLOAT NOT NULL DEFAULT 75,
   --TW_Gold FLOAT NOT NULL DEFAULT 82.5,
   --TW_Platinum FLOAT NOT NULL DEFAULT 90,
   --TW_Ruby FLOAT NOT NULL DEFAULT 95,
   --TW_Diamond FLOAT NOT NULL DEFAULT 97.5,

--	AVG_DEPTH : For those who use this, have them found 15-30% above and below AVG_DEPTH

);